### ISSUE TITLE
ErrorCode enum not exported

### ISSUE THREAD

**Issue by matteofrana** [react-dropzone/react-dropzone#1094]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
The enum `ErrorCode` is not exported by the library, but only in the typings file

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `import { ErrorCode } from 'react-dropzone'`
2. `if (errorCode === ErrorCode.FileInvalidType) {...}`

**What is the expected behavior?**
It finds ErrorCode exported from 'react-dropzone', instead VSCode finds the import (from the typings) but when you run the project it throws an error because the enum is not exported.

**Comment by rolandjitsu** [comment]
Should have been fixed in https://github.com/react-dropzone/react-dropzone/pull/1092.

**Comment by matteofrana** [comment]
I installed the latest version, v11.4.1, and the `ErrorCode` enum is still not exported.

**Comment by cherepanov** [comment]
ErrorCode is not re-exported from index, i think it should. 
it can be imported only this way

```
import { ErrorCode } from 'react-dropzone/dist/es/utils';
```

**Comment by strmer15** [comment]
Yeah, just noticed this too when I was testing with the change today, I'll open another PR to fix.
