### ISSUE TITLE
setState is called after the component is unmounted

### ISSUE THREAD

**Issue by leogiertz** [react-dropzone/react-dropzone#689]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Getting a warning from React that the drop zone is calling setState after it has been unmounted. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. In a component, mount a dropzone with an onDrop callback.
2. Drop a file on it
3. In the callback, unmount the dropzone (i.e. to display a loading indicator instead of a dropzone)
4. Check the console.

**What is the expected behavior?**
That React doesn't complain.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Nope.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Introduced in Dropzone 5.1.1: https://github.com/react-dropzone/react-dropzone/commit/cb99c8a9151810544e7be7fa5c68cf2f0dcc27a5

From react-dropzone's perspective, I'm not certain it's safe to assume that the component still will be mounted after having fired the callback since the callback might cause side effects such as unmounting it. One solution could be to move the calls to setState to before the callbacks has been fired.

**Comment by rolandjitsu** [comment]
Fixed in https://github.com/react-dropzone/react-dropzone/pull/690.

**Comment by aggregate1166877** [comment]
Still getting this on version `14.2.3` when using the `wrapper component for the hook` example in the README:
```
Warning: Can't perform a React state update on an unmounted component. This is
a no-op, but it indicates a memory leak in your application. To fix, cancel all
subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Dropzone (created by MyComponent1)
    in FileDragDrop (created by MyComponent2)
```
