### ISSUE TITLE
`onDragLeave` Usage with React component throws console error and fails to reset styling

### ISSUE THREAD

**Issue by Brandonprs** [react-dropzone/react-dropzone#741]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug

**What is the current behavior?**

`onDropLeave` inherit functionality broken in new versions of React (16.5). Leaving the dropzone produces the following console error:
```
index.js:181 Uncaught TypeError: _this.node.contains is not a function
    at index.js:181
    at Array.filter (<anonymous>)
    at Dropzone._this.onDragLeave (index.js:180)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:265)
    at executeDispatch (react-dom.development.js:571)
    at executeDispatchesInOrder (react-dom.development.js:596)
    at executeDispatchesAndRelease (react-dom.development.js:695)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:704)
    at forEachAccumulated (react-dom.development.js:676)
    at runEventsInBatch (react-dom.development.js:844)
    at runExtractedEventsInBatch (react-dom.development.js:852)
    at handleTopLevel (react-dom.development.js:5025)
    at batchedUpdates$1 (react-dom.development.js:19916)
    at batchedUpdates (react-dom.development.js:2246)
    at dispatchEvent (react-dom.development.js:5105)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add dropzone with base functionality to a new React component.
2. Drag file over dropzone.
3. Still dragging, move mouse to non-dropzone area.

**What is the expected behavior?**

That the `isDropActive` bool resets to `false` and the dropzone is de-activated without any errors.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
react-dropzone v. 8.0.0
Chrome v. 71

**Comment by Studio384** [comment]
I am experiencing the same error be it with different tracebacks:
```
TypeError: _this.node.contains is not a function[Meer info] 8 bundle.js line 20986 > eval:102:37
	Dropzone/_this.onDragLeave/_this.dragTargets< index.js:96
	filter self-hosted:312:17
	Dropzone/_this.onDragLeave index.js:95
	callCallback react-dom.development.js:149
	invokeGuardedCallbackDev react-dom.development.js:199
	invokeGuardedCallback react-dom.development.js:256
	invokeGuardedCallbackAndCatchFirstError react-dom.development.js:270
	executeDispatch react-dom.development.js:561
	executeDispatchesInOrder react-dom.development.js:583
	executeDispatchesAndRelease react-dom.development.js:680
	executeDispatchesAndReleaseTopLevel react-dom.development.js:688
	forEachAccumulated react-dom.development.js:662
	runEventsInBatch react-dom.development.js:816
	runExtractedEventsInBatch react-dom.development.js:824
	handleTopLevel react-dom.development.js:4824
	batchedUpdates$1 react-dom.development.js:19260
	batchedUpdates react-dom.development.js:2150
	dispatchEvent react-dom.development.js:4903
	dispatchEvent self-hosted:1018:17
```

And:
```
TypeError: _this.node.contains is not a function[Meer info] bundle.js line 20986 > eval:48:25
	Dropzone/_this.onDocumentDrop index.js:42
```

**Comment by fanixk** [comment]
I'm experiencing the issue only when using styled-components to style my Container.
(styled-components v3.4.10)

**Comment by Brandonprs** [comment]
@rolandjitsu working on it, sorry. Having issues getting the Dropzone component to render properly in CodePen.

**Comment by padrisimo** [comment]
> I'm experiencing the issue only when using styled-components to style my Container.
> (styled-components v3.4.10)

Remember, if u use **styled-components** u may pass a custom refKey like `{...getRootProps({ refKey: 'innerRef' })}` instead of  just `{...getRootProps()}` and all this problems should be solved.

**Comment by rolandjitsu** [comment]
@Brandonprs is this issue still valid? Or did @padrisimo's suggestion work for you?

**Comment by Brandonprs** [comment]
Still an issue, though I spent some time trying to get the `Dropzone` component working (in CodeSandbox, CodePen, etc.) without luck, so I gave up for a while. It's not a huge pressing issue for us though I understand it's something I'll need figure out eventually.

**Comment by skystar0227** [comment]
I saw the same error with Material UI.
For my case, @padrisimo's comment is useful to solve it.

`getRootProps()` seems to provide an attribute `ref` or an attribute with a name secified with `refKey`.

But almost all Material UI's comonents cannot receive `ref` directly. It may be just ignored.

```jsx
<MUIComponent {...getRootProps()} /> {/* Error: 'ref' won't work */} 
```

Material UI provides an interface component `RootRef` to pass a attribute`ref` to a child component. This is an offical way.
 
So my solution is the following:

```jsx
const { ref, ...rootProps } = getRootProps();
<RootRef rootRef={ref}>
  <MUIComponent {...rootProps} />
</RootRef> 
```

There may be simiar solutions if you are trying to use `getRootProps()` as attributes for a component which cannot receive `ref`.

**Comment by Brandonprs** [comment]
@skystar0227 That fixed my issue! I think my issue with the CodeSandbox was the material UI components.

**Comment by ARChilton** [comment]
You were right it was the ref. I am using Emotion to style my components and so the ref needed to be innerRef just like the example here: https://github.com/react-dropzone/react-dropzone#custom-refkey

Thank you for pointing me in the right direction.
