### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by emjaksa** [react-dropzone/react-dropzone#775]
**Do you want to request a *feature* or report a *bug*?**

- [ x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Version 10.0.0 cause a document undefined error with server side rendering.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Enable application with SSR
1. Use react-dropzone
1.

**What is the expected behavior?**
no undefined error

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Most likely caused from changing /src/utils/index.js

from
```
export const supportMultiple =
  typeof document !== 'undefined' && document && document.createElement
    ? 'multiple' in document.createElement('input')
    : true
```

to

```
export const supportMultiple = 'multiple' in document.createElement('input')
```

**Comment by rolandjitsu** [comment]
Hmmm, the `document` object is also used by the [hook](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L432), so it's strange that it's not an issue there.

Let me just try it out.

**Comment by emjaksa** [comment]
@rolandjitsu I can't provide an example because online code editors don't do server side rendering.

**Comment by chill5018** [comment]
I am seeing the same error after upgrading react-dropzone. Not sure if this helps, but here is the stacktrace I am getting. 

<img width="321" alt="screenshot 2019-03-06 at 11 17 04" src="https://user-images.githubusercontent.com/7937980/53873875-8ca0bc80-4001-11e9-8f67-3fd1c939c77d.png">

**Comment by rolandjitsu** [comment]
@emjaksa could you create a repo and share that?

**Comment by chill5018** [comment]
https://github.com/chill5018/next-react-dropzone-demo Here you go @rolandjitsu

**Comment by gauravtiwari** [comment]
`useEffects` are run after a component is mounted, which is safe for SSR however, the code above gets parsed by the browser on the page load and that's the cause of the error. Adding a guard clause that checks for DOM would solve the problem. 

This is the cause of the issue: 

```js
export const supportMultiple =
  typeof document !== 'undefined' && document && document.createElement
    ? 'multiple' in document.createElement('input')
    : true
```

**Comment by rolandjitsu** [comment]
@chill5018 thanks.
@gauravtiwari that will get coverage down as it's not easy to test in Jest. So we need a more elegant solution. I'll take a look tomorrow, or you're welcome to make a PR with a solution that wouldn't affect coverage.

**Comment by emjaksa** [comment]
@rolandjitsu sorry, didn't think of that but looks @chill5018 create one for me. Thanks

**Comment by Chris533** [comment]
It doesn't work, 10.0.0, with next,

**Comment by rolandjitsu** [comment]
@Chris533 working on it. There's another error, besides the one reported here and I'm trying to track it down.

**Comment by Chris533** [comment]
```
import dynamic from 'next/dynamic'

const DynamicComponentWithNoSSR = dynamic(() => import('../components/hello3'), {
  ssr: false
})

function Home() {
  return (
    <div>
      <Header />
      <DynamicComponentWithNoSSR />
      <p>HOME PAGE is here!</p>
    </div>
  )
}

export default Home
```

Thanks, I user this finger out.

**Comment by KaiHotz** [comment]
Just change `'multiple' in document.createElement('input')` to `'multiple' in React.createElement('input')` and it should solve the problem

**Comment by ethanmick** [comment]
Same issue here, `10.0.0` on `next@latest`.

**Comment by rolandjitsu** [comment]
This particular issue should be fixed now. Please let me know if you encounter any other issues related to SSR.

**Comment by wheredoesyourmindgo** [comment]
I'm still getting the same error with 10.0.2. Maybe I'm missing something? Using the _useDropzone_ hook with Next.js. A demo repo illustrating the problem when the index page is loaded (via SSR) can be found at [demo-repo](https://github.com/wheredoesyourmindgo/dzdemo)

**Comment by Dakkers** [comment]
@wheredoesyourmindgo this wasn't fixed in 10.0.2 (check the changelog). you could use the branch @rolandjitsu made and try it out

**Comment by wheredoesyourmindgo** [comment]
ahh. I see. Thx @Dakkers .

**Comment by Yaxian** [comment]
@Chris533 , it helps me, thx.
@Dakkers try this:
```
import dynamic from 'next/dynamic';
const Dropzone = dynamic(() => import('react-dropzone'), { ssr: false });

const App = () => {
    return (
       <Dropzone>
            {({ getRootProps, getInputProps }) => (
                <div {...getRootProps()} className={classes.dropzone}>
                  <input {...getInputProps()} />
                  <div className={classes.itemOutContainer}>
                    <div className={classes.itemContainer}>
                      <div className={cns(classes.item, classes.itemCreate)}>
                        uploading files
                      </div>
                    </div>
                  </div>
                </div>
            )}
       </Dropzone>
    );
}
```
