### ISSUE TITLE
React-Dropzone - Error: Invalid hook call

### ISSUE THREAD

**Issue by anthony-langford** [react-dropzone/react-dropzone#837]
**Do you want to request a *feature* or report a *bug*?**

- [X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
The current behaviour while using the latest version of react-dropzone (10.1.5) is the following error on attempting to render the component in a class component using the example in the docs.

`
Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.
`

`
The above error occurred in the <Dropzone> component:
    in Dropzone
`

```
export class UploadFile extends React.Component {
  render() {
    return (
      <Dropzone onDrop={acceptedFiles => console.log(acceptedFiles)}>
        {({ getRootProps, getInputProps }) => (
          <section>
            <div
              {...getRootProps({
                accept: "application/pdf,image/jpg,image/jpeg,image/png",
                multiple: true
              })}
            >
              <input {...getInputProps()} />
              <p>Drop files here</p>
            </div>
          </section>
        )}
      </Dropzone>
    );
  }
```

**Comment by aarshaw** [comment]
@anthony-langford were you able to find a solution/workaround for this?

**Comment by anthony-langford** [comment]
@aarshaw Yes, I rolled back the version to before hooks were implemented in this package so I could use it with a class-based component 😋

**Comment by aarshaw** [comment]
That's sorted it for me, thanks

**Comment by ArcherBG** [comment]
I have upgraded to react 16.8 so react-dropzone@8.1.0 did not work, so I downgraded it at version 7.0.0

**Comment by rolandjitsu** [comment]
@anthony-langford please provide a proper example illustrating the issue. The main [react-dropzone.js](https://react-dropzone.js.org) docs works just fine, so it must be something related to your setup that causes the issue.

**Comment by alexsandr1992** [comment]
I have same problem.
My recommendation: check package react-dom. He also must be updated to version >=16.8 (in my case to 16.8.6).
and then problem was resolved

**Comment by rolandjitsu** [comment]
@alexsandr1992 in [package.json#L87](https://github.com/react-dropzone/react-dropzone/blob/master/package.json#L87), react is required as peer dep. and is set to be be `>= 16.8`, which means `react-dom` **must** be at least the same. I thought this would be self explanatory.

Furthermore, if you read the [hooks intro](https://reactjs.org/docs/hooks-intro.html), right at the top, there is a note which says:
> React 16.8.0 is the first release to support Hooks. When upgrading, don’t forget to update all packages, including React DOM.

I'm closing this as it's not really an issue with the lib. I might, though, add a note somewhere in the docs to let ppl know you must use a proper version of react (and react-dom).

**Comment by iamrahulroy** [comment]
@rolandjitsu in my project, react & react-dom are at the same version i.e 16.8.6, but I'm still facing the same issue.

**Comment by k4st0r42** [comment]
> @rolandjitsu in my project, react & react-dom are at the same version i.e 16.8.6, but I'm still facing the same issue.

I am in the same situation...

**Comment by rolandjitsu** [comment]
@k4st0r42 please clear the npm/yarn cache and your node modules and try to reinstall. Also make sure that you're on the latest version of react-dropzone.

**Comment by ArcherBG** [comment]
I had messed up my package.json and package-lock.json. I revertedn the package-lock.json file to prev version i was using and reinstalled the node modules. This worked for me.

**Comment by iamrahulroy** [comment]
@k4st0r42 try this https://reactjs.org/warnings/invalid-hook-call-warning.html

**Comment by merges** [comment]
Has any progress been made on this issue? I have the same problem even with `react` and `react-dom` at `16.8.6`.

**Comment by GunnarPDX** [comment]
I was able to fix this issue by deleting `node_modules` and then running `npm install`

**Comment by JuanIrache** [comment]
Happening on Electronjs with react and react-dom 16.13.1 with both the wrapper component and the hook

```
import React from 'react';
import Dropzone from 'react-dropzone';

export default () => (
  <div className="LoadFiles">
    <Dropzone onDrop={acceptedFiles => console.log(acceptedFiles)}>
      {({ getRootProps, getInputProps }) => (
        <section>
          <div {...getRootProps()}>
            <input {...getInputProps()} />
            XXX
          </div>
        </section>
      )}
    </Dropzone>
  </div>
);
```

Tried the suggested solutions but still...

> K:\vsprojs\better-gauges\node_modules\react\cjs\react.development.js:1465 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
>     at resolveDispatcher (K:\vsprojs\better-gauges\node_modules\react\cjs\react.development.js:1465:13)
>     at Object.useRef (K:\vsprojs\better-gauges\node_modules\react\cjs\react.development.js:1504:20)
>     at props (K:\vsprojs\better-gauges\node_modules\react-dropzone\src\index.js:384:38)
>     at K:\vsprojs\better-gauges\node_modules\react-dropzone\src\index.js:45:35
>     at renderWithHooks (http://localhost:9080/renderer.js:89183:18)
>     at updateForwardRef (http://localhost:9080/renderer.js:91196:20)
>     at beginWork (http://localhost:9080/renderer.js:93025:16)
>     at HTMLUnknownElement.callCallback (http://localhost:9080/renderer.js:74568:14)
>     at Object.invokeGuardedCallbackDev (http://localhost:9080/renderer.js:74617:16)
>     at invokeGuardedCallback (http://localhost:9080/renderer.js:74672:31)

Thank you

**Comment by JuanIrache** [comment]
Here's a minimal example to reproduce the error (at least as minimal as I could make it with electron+react+webpack):

https://github.com/JuanIrache/dropzone-test

Note that I use hooks all the time in this project with no problems.

Thanks

**Comment by mohantyArpit** [comment]
I don't know if this will help anyone , but in my case i had initially installed the package in my root folder, 
so the structure was like inside root project there was the Front end project and back-end project all npm ,
there were no import error even though it was in root.But while rendering it would throw the invalid hook issue.
But when i reinstalled it in my FE project it worked fine
